spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mvc_sec
    username: root
#    password:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
################
#####Only for schema-generation with hibernate:
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: ./src/main/resources/db_create.sql