version: '3'
services:
  persist-db:
    image: mysql:latest
    container_name: mvc-sec
    volumes:
      - /home/joe/Dokumente/programming/dockerdata/mvc-sec:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=mvc_sec
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password
